### ISSUE TITLE
Error continues to occur.

### ISSUE THREAD

**Issue by Arynn24** [SM64-STROOP/STROOP#15]
I have Mupen64 5.1, and STROOP is the newest version... but it continues to give me this error:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at SM64_Diagnostic.StroopMainForm.AttachToProcess(Process process)
   at SM64_Diagnostic.StroopMainForm.buttonConnect_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Can anyone help me here?

**Comment by danebouchie** [comment]
STROOP doesn't work with Mupen 0.5.1. Only Mupen 0.5 (re-recording). You can find a link to that version from tasvideos.org [here](http://adelikat.tasvideos.org/emulatordownloads/mupen64-rr/Mupen64%20v8%20installer.zip).

**Comment by Arynn24** [comment]
Thank you for giving me a way to download it, I no longer have problems :D

**Comment by danebouchie** [comment]
Awesome! Ur welcome!
